CREATE TABLE dbo.EducationalOrganisation (
	Id					UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	Name				NVARCHAR(100) NOT NULL,
	EducationalType		NVARCHAR(100) NOT NULL,
	AddressLine1		NVARCHAR(100) NOT NULL,
	AddressLine2		NVARCHAR(100) NOT NULL,
	AddressLine3		NVARCHAR(100) NULL,
	Town				NVARCHAR(100) NOT NULL,
	County				NVARCHAR(100) NOT NULL,
	PostCode			NVARCHAR(10) NOT NULL,
	URN					NVARCHAR(6) NOT NULL,
	LepCode				NVARCHAR(50) NOT NULL
)
