CREATE TABLE dbo.EducationalOrganisation (
	Id					UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	Name				NVARCHAR(100) NULL,
	EducationalType		NVARCHAR(100) NULL,
	AddressLine1		NVARCHAR(100) NULL,
	AddressLine2		NVARCHAR(100) NULL,
	AddressLine3		NVARCHAR(100) NULL,
	Town				NVARCHAR(100) NULL,
	County				NVARCHAR(100) NULL,
	PostCode			NVARCHAR(10) NULL,
	URN					NVARCHAR(6) NULL,
	LepCode				NVARCHAR(50) NULL
)
