CREATE TABLE dbo.LEPSData (
	Id					INT NOT NULL PRIMARY KEY IDENTITY,
	LepCode				NVARCHAR(50) NOT NULL DEFAULT (''),
	LepName				NVARCHAR(150) NOT NULL DEFAULT (''),
	EntityEmail			NVARCHAR(100) NOT NULL DEFAULT (''),
	Region				NVARCHAR(100) NOT NULL DEFAULT (''),
	AddressLine1		NVARCHAR(250) NOT NULL DEFAULT (''),
	AddressLine2		NVARCHAR(250) NOT NULL DEFAULT (''),
	AddressLine3		NVARCHAR(250) NOT NULL DEFAULT (''),
	Country				NVARCHAR(250) NOT NULL DEFAULT (''),
	PostCode			NVARCHAR(10) NOT NULL DEFAULT (''),
	PhoneNumber			NVARCHAR(50) NOT NULL DEFAULT (''),
	TechnicalContact	NVARCHAR(250) NOT NULL DEFAULT (''),
	PostAPIUrl			NVARCHAR(250) NOT NULL DEFAULT (''),
	APIKeyName			NVARCHAR(150) NOT NULL DEFAULT (''),
	APIKeyValue			NVARCHAR(150) NOT NULL DEFAULT (''),
	DateAdded			DATETIME NOT NULL DEFAULT GETDATE()
)