CREATE TABLE dbo.LEPSCoverage (
	Id					INT NOT NULL PRIMARY KEY IDENTITY,
	LEPSId				INT NOT NULL ,
	Postcode			NVARCHAR(10) NOT NULL DEFAULT (''),
	IsDeleted           BIT NOT NULL DEFAULT 0,
	DateAdded			DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT FK_LEPSCoverage_LEPSData 
        FOREIGN KEY(LEPSId) 
        REFERENCES dbo.LEPSData(Id)
)
GO

CREATE NONCLUSTERED INDEX IX_LEPSCoverage_Postcode_IsDeleted
ON dbo.LEPSCoverage (Postcode, IsDeleted);
GO