CREATE TABLE dbo.LEPSCoverage (
	Id					INT NOT NULL PRIMARY KEY IDENTITY,
	LEPSId				INT NOT NULL ,
	PostInCode			NVARCHAR(10) NOT NULL DEFAULT (''),
	IsDeleted           BIT NOT NULL DEFAULT 0,
	DateAdded			DATETIME NOT NULL DEFAULT GETDATE()
	CONSTRAINT FK_LEPSCoverage_LEPSData 
        FOREIGN KEY(LEPSId) 
        REFERENCES dbo.LEPSData(Id)
)