CREATE TABLE dbo.MetricsFlag (
	Id				INT NOT NULL PRIMARY KEY IDENTITY,
	FlagName		NVARCHAR(150) NOT NULL DEFAULT (''),
	FlagCode		NVARCHAR(100) NOT NULL DEFAULT (''),
	IsActive		BIT NOT NULL DEFAULT (0),
	DateAdded		DATETIME NOT NULL DEFAULT GETDATE()
)