CREATE TABLE [dbo].[Survey]
(
	Id					INT NOT NULL PRIMARY KEY,
	Title               NVARCHAR(250) NOT NULL,
	Description			NVARCHAR(250) NOT NULL,
	StartDate			DATETIME NULL,
	EndDate				DATETIME NULL,
	IsActive			BIT NOT NULL DEFAULT (0),
	DateAdded			DATETIME NOT NULL DEFAULT GETDATE()
)